### ISSUE TITLE
Running Docker Image

### ISSUE THREAD

**Issue by stvhanna** [mpolden/echoip#117]
I'm having trouble running the docker image. Any help would be greatly appreciated!

```
$ docker run mpolden/echoip -a ./GeoLite2-ASN.mmdb -c ./GeoLite2-City.mmdb -f ./GeoLite2-Country.mmdb
echoip: open ./GeoLite2-Country.mmdb: no such file or directory
```

Having a `docker-compose.yml` would make this much easier to run:
```
version: "3.7"
services:
  echoip:
    image: mpolden/echoip
    command: "echoip -a ./GeoLite2-ASN.mmdb -c ./GeoLite2-City.mmdb -f ./GeoLite2-Country.mmdb"
    ports:
      - "8080:8080"
    restart: unless-stopped
```
