### ISSUE TITLE
Docker compose file

### ISSUE THREAD

**Issue by ShlomiPorush** [mpolden/echoip#158]
After I saw that there was no documentation how to run it in docker compose.. So, Enjoy.

```
version: '3.7'

services:
  echoip:
    image: mpolden/echoip
    command: "-C 0 -p -r -H X-Forwarded-For -a /data/GeoLite2-ASN.mmdb -c /data/GeoLite2-City.mmdb -f /data/GeoLite2-Country.mmdb"
    ports:
      - 8080:8080
    volumes:
      - ./data:/data:ro
  
  # this container needs to runs only once or whan you want to update Geo databases
  maxmind:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_ACCOUNT_ID= # get your own account from https://www.maxmind.com/
      - GEOIPUPDATE_LICENSE_KEY= # get your own key from https://www.maxmind.com/
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
    volumes:
      - ./data:/usr/share/GeoIP
```
