### ISSUE TITLE
How can I get round the CORS issue (Self Hosted)

### ISSUE THREAD

**Issue by SamB-GB** [mpolden/echoip#175]
I have this self hosted but still encounter the CORS issue when on sub domains...

Access to fetch at 'https://sub.mydomain.com/' from origin 'https://sub.mydomain.com/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by air3ijai** [comment]
⚠️ **Please make sure to use SSL and adjust configuration by your needs** ⚠️

A quick workaround to test how it works.

<details>
<summary>steps and details</summary>

 1. Download GeoLite DBs and put them into `geodb` folder

 2. Create `nginx.conf` file
    ```shell
    vi nginx.conf
    ```
    ```nginx
    user                nginx;
    worker_processes    auto;

    error_log    /var/log/nginx/error.log notice;
    pid          /var/run/nginx.pid;

    events {
        worker_connections    1024;
        accept_mutex          off;
        use                   epoll;
    }

    http {
        include         /etc/nginx/mime.types;
        default_type    application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile             on;
        keepalive_timeout    65;

        upstream echoip {
            server    echoip:8080 fail_timeout=0;
        }

        server {

            location / {
                proxy_set_header    X-Forwarded-For      $proxy_add_x_forwarded_for;
                proxy_set_header    X-Forwarded-Proto    $scheme;
                proxy_set_header    Host                 $host;
                proxy_redirect      off;
                proxy_pass          http://echoip/;

                proxy_set_header    X-Forwarded-Host    $server_name;
                proxy_set_header    X-Real-IP           $remote_addr;

                # Preflighted requests
                if ($request_method = OPTIONS ) {
                    add_header 'Access-Control-Allow-Origin'  '*';
                    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, HEAD';
                    add_header 'Access-Control-Allow-Headers' 'Authorization, Origin, X-Requested-With, Content-Type, Accept';

                    return 200;
                }

                if ($request_method ~* '(GET|POST)') {
                    add_header 'Access-Control-Allow-Origin' '*';
                }
            }
        }
    }
    ```

 3. Create `docker-compose.yaml` file
    ```shell
    vi docker-compose.yaml
    ```
    ```yaml
    services:
      # echoip
      echoip:
        image: mpolden/echoip
        container_name: echoip
        pull_policy: always
        command:
          - -l
          - :8080
          - -p
          - -H
          - X-Real-IP
          - -r
          - -t
          - html
          - -a
          - /geodb/GeoLite2-ASN.mmdb
          - -c
          - /geodb/GeoLite2-City.mmdb
          - -f
          - /geodb/GeoLite2-Country.mmdb
        volumes:
          - ./geodb:/geodb
        logging:
          driver: json-file
          options:
            max-size: 100m
            max-file: 5
        networks:
          - echoip

      # Nginx
      nginx:
        image: nginx
        container_name: nginx
        ports:
          - 80:80
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        logging:
          driver: json-file
          options:
            max-size: 100m
            max-file: 5
        networks:
          - echoip

    networks:
      echoip:
        driver: bridge
    ```

 4. Run the following command to start the services
    ```shell
    docker-compose up -d
    ```

 5. Test the service
    http://localhost

</details>

Actually that feature was added [Sep 17, 2015](https://github.com/mpolden/echoip/commit/40df3e5a386569cf7bf7a1477c61769fa1fc3d46) and removed [Apr 17, 2016](https://github.com/mpolden/echoip/commit/9d8a541caf48dff9538754a72ce9a9dd5a667dd4)

- #7
- #17
- #49
- #119

It would be very useful to have a native cli argument for that (`-x, --cors`), not complicate the things during the tests.
